version: '3'

services:
  db:
    image: mysql:5.7
    ports:
     - "3306:3306"
    volumes:
     - ./sqldumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
     - "8001:80"
    environment:
     - PMA_USER = user
     - PMA_PASSWORD = password
     - PMA_HOST = db
    depends_on:
     - db
