version: '3'

services:
  db:
    image: mysql:5.7
    command: --sql-mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    ports:
     - "3306:3306"
    volumes:
     - ./sqldumps:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
     - "8080:80"
    environment:
     - PMA_USER = user
     - PMA_PASSWORD = password
     - PMA_HOST = db
    depends_on:
     - db
